spring:
  application:
    name: search

client:
  kakao-place-search:
    url: https://dapi.kakao.com/v2
    timeout: 3000
    api-key: {your-api-key}
  naver-place-search:
    url: https://openapi.naver.com/v1
    timeout: 3000
    client-id: {your-client-id}
    client-secret: {your-client-secret}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
